package com.mubir.order.domain;

public enum CarOrderStatusEnum {

    NEW,VALIDATED,VALIDATION_EXCEPTION,ALLOCATED,ALLOCATION_EXCEPTION,
    PENDING_INVETORY,PICKED_UP,DELIVERED,DELIVERY_EXCEPTION
}
