DROP DATABASE IF EXISTS carorderservice;
DROP USER IF EXISTS `car_order_service`@`%`;
CREATE DATABASE IF NOT EXISTS carorderservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `car_order_service`@`%` IDENTIFIED WITH mysql_native_password BY '12345678';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `carorderservice`.* TO `car_order_service`@`%`;
FLUSH PRIVILEGES;